version: '3'
services:
  scanner:
    image: alpine:latest
    networks:
       - backend
  
  postgresdb:  
   image: postgres:alpine
   ports:
       - "5432:5432"
   environment:
       - POSTGRES_PASSWORD=pp
   networks:
       - backend

  application:
   image: tudi/tsvelte:golangadmin 
   networks:
       - backend

networks:
  backend:
    driver: "bridge"
